### PR TITLE
Server stored key and enable edit without API key

### PR DESCRIPTION
**Pull request by phuongnq**

### CODE REVIEW

**Comment by phuongnq** [comment]
no_api_key
with_api_key

**Comment by russdanner** [comment]
My preference would be to NOT SHOW search if the API key is missing (rather than show an error)

**Comment by phuongnq** [comment]
Updated to hide search if the API key is missing. In this case, if we input a full link, it will populate youtube ID from the link url.

**Comment by phuongnq** [comment]
Closed as not maintenanced.

**Pull request closed without merging**
